import { User } from '@/models/User';

export const sampleUser: User = {
  $id: 'user123',
  $createdAt: new Date('01-01-2024').toISOString(),
  $updatedAt: new Date('01-01-2024').toISOString(),
  $collectionId: 'users',
  $databaseId: 'db1',
  $permissions: [],
  name: 'Guest User',
  country: 'Canada',
  countryCode: 'CA',
  gender: 'male',
  birthdate: new Date('1995-05-15'),
  username: 'langx',
  languageArray: ['English', 'French'],
  motherLanguages: ['English'],
  studyLanguages: ['French', 'Spanish'],
  languages: [
    {
      name: 'English',
      proficiency: 'native',
      $id: '1',
      $collectionId: 'languages',
      $databaseId: 'db1',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: [],
      code: 'en',
      level: -1,
      motherLanguage: true,
      nativeName: 'English',
      userId: 'user123',
    },
    {
      name: 'French',
      proficiency: 'intermediate',
      $id: '2',
      $collectionId: 'languages',
      $databaseId: 'db1',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: [],
      code: 'fr',
      level: 1,
      motherLanguage: false,
      nativeName: 'French',
      userId: 'user123',
    },
    {
      name: 'Spanish',
      proficiency: 'beginner',
      $id: '3',
      $collectionId: 'languages',
      $databaseId: 'db1',
      $createdAt: new Date().toISOString(),
      $updatedAt: new Date().toISOString(),
      $permissions: [],
      code: 'es',
      level: 3,
      motherLanguage: false,
      nativeName: 'Spanish',
      userId: 'user123',
    },
  ],
  badges: ['polyglot', 'early_bird'],
  aboutMe:
    'Passionate about languages and cultures. Love to travel and meet new people.',
  lastSeen: new Date(new Date().getTime() - 60000),
  totalUnseen: 5,
  totalUnseenArchived: 2,
  notifications: ['new_message', 'new_friend_request'],
  notificationsArray: ['new_message', 'new_friend_request'],
  blockedUsers: [],
  archivedRooms: [],
  privacy: [],
  contributors: [],
  sponsor: false,
  streaks: {
    dayStreak: 10,
    userId: 'user123',
    lastActivity: new Date('2024-07-01'),
    $id: 'streak1',
    $collectionId: 'streaks',
    $databaseId: 'db1',
    $createdAt: new Date().toISOString(),
    $updatedAt: new Date().toISOString(),
    $permissions: [],
  },
  profilePic: '652d582c65bb47ac5de0',
  otherPics: ['652d582c65bb47ac5de0', '652d582c65bb47ac5de0'],
};
