import { createHash } from 'node:crypto'
import {
  DISCOVERY_BOOSTED_FRESH_MS,
  DISCOVERY_BOOSTED_ROTATION_MS,
  DISCOVERY_BOOSTED_TIERS,
  type PlanTier,
} from '@langx/shared'

/**
 * What the ordering needs to know about a candidate.
 *
 * Structural rather than `Profile`, so the tests can pass three-field literals
 * and the call site can hand over documents without a mapping pass.
 */
export interface BoostedCandidate {
  _id: string
  entitlement: { tier: PlanTier }
  stats: { lastActiveAt: Date }
  avatarUrl?: string
  bio?: string
}

/**
 * A rotation value for one viewer, one profile and one hour.
 *
 * SHA-256 rather than the small `Math.imul` generator `gift.test.ts` uses:
 * that one is seeded by a single number, and seeding it from three strings
 * would mean first writing a folding hash and then having to argue its
 * avalanche behaviour. `node:crypto` is already how this codebase hashes a
 * string, and thirty-two bits off the front of a digest is all an order needs.
 */
function rotationOf(viewerId: string, candidateId: string, bucket: number): number {
  return createHash('sha256')
    .update(`${viewerId}:${candidateId}:${bucket}`)
    .digest()
    .readUInt32BE(0)
}

/**
 * Whether this candidate has earned the front of the strip: a real photo,
 * something written, and a visit inside the week.
 *
 * `avatarUrl` is only ever an uploaded file — `assertOwnBucket` refuses
 * anything else on every write path, and the drawn fallback is generated by
 * the client from the id and never stored — so its presence is exactly "this
 * person put up a photo", with no URL to inspect.
 *
 * The bio is trimmed because an empty string is reachable: clearing the field
 * in the editor writes `''` rather than removing it.
 */
function readyToLead(candidate: BoostedCandidate, freshFrom: number): boolean {
  return Boolean(
    candidate.avatarUrl &&
    candidate.bio?.trim() &&
    candidate.stats.lastActiveAt.getTime() >= freshFrom,
  )
}

/**
 * The strip's presentation order, for one viewer at one moment.
 *
 * Three bands, outermost first:
 *
 * 1. **Tier.** Polyglot above Fluent, always. The paywall sells that sentence
 *    and `rules.test.ts` pins the list it comes from, so it is a hard band and
 *    nothing below it may cross one.
 * 2. **Ready to lead, or not** — a photo, something written, and a visit
 *    inside `DISCOVERY_BOOSTED_FRESH_MS`. All three, in one band rather than
 *    three, and that is the load-bearing decision here. Mutual language fit
 *    leaves a viewer one to four candidates, so every extra band halves the
 *    chance that two of them share a bucket, and a candidate alone in its
 *    bucket has a fixed position — which is the permanent order this whole
 *    ordering exists to break. Two buckets is what keeps the rotation real.
 *
 *    The photo and the bio are not a new definition of a good profile:
 *    `promotions.ts` already nudges an account with no `avatarUrl` on the
 *    grounds that a faceless one is scrolled past, and onboarding calls the
 *    avatar and the bio "the two things that make a first impression". A
 *    placement somebody pays for should lead with a card worth tapping and a
 *    profile worth landing on. Nobody is excluded for failing this — they paid,
 *    so they are in the strip either way; they just do not lead it.
 *
 *    Truthiness, not a minimum length: a one-character bio would technically
 *    pass, and the fix for that is a threshold in `packages/shared` on the day
 *    somebody actually does it, not one invented now for a problem nobody has.
 * 3. **Rotation**, seeded on the viewer, the profile and the hour. The viewer
 *    is in the seed for the reason that matters at this size: one person sees
 *    very few hours in a day, so if the seed were time alone the exposure
 *    would only even out over a week. With the viewer in it, a subscriber is
 *    leading somebody's strip within the hour.
 *
 * `_id` is the last term and is not decoration: two equal hashes would
 * otherwise leave the result to the engine's sort, and "the cards do not move
 * when I pull to refresh" would stop being true for reasons nobody could
 * reproduce.
 *
 * `now` carries both the freshness cutoff and the rotation bucket, so this has
 * no clock of its own and a test can ask for any hour it likes.
 */
export function orderBoosted<T extends BoostedCandidate>(
  candidates: readonly T[],
  viewerId: string,
  now: Date,
): T[] {
  const freshFrom = now.getTime() - DISCOVERY_BOOSTED_FRESH_MS
  const bucket = Math.floor(now.getTime() / DISCOVERY_BOOSTED_ROTATION_MS)

  // Decorated once per candidate rather than inside the comparator, which
  // would hash O(n log n) times for an answer that cannot change.
  const ranked = candidates.map((candidate) => ({
    candidate,
    // `-1` is unreachable: the pipeline's `$match` admits these tiers only.
    tier: DISCOVERY_BOOSTED_TIERS.findIndex((tier) => tier === candidate.entitlement.tier),
    behind: readyToLead(candidate, freshFrom) ? 0 : 1,
    rotation: rotationOf(viewerId, candidate._id, bucket),
  }))

  return ranked
    .toSorted(
      (a, b) =>
        a.tier - b.tier ||
        a.behind - b.behind ||
        a.rotation - b.rotation ||
        (a.candidate._id < b.candidate._id ? -1 : a.candidate._id > b.candidate._id ? 1 : 0),
    )
    .map((entry) => entry.candidate)
}
