export enum ActionTypes {
  GET_ROOM = '[Room] Get Room',
  GET_ROOM_SUCCESS = '[Room] Get Room Success',
  GET_ROOM_FAILURE = '[Room] Get Room Failure',
  CREATE_ROOM = '[Room] Create Room',
  CREATE_ROOM_SUCCESS = '[Room] Create Room Success',
  CREATE_ROOM_FAILURE = '[Room] Create Room Failure',
  SELECT_ROOM = '[Room] Select Room',
  GET_ROOMS = '[Room] Get Rooms',
  GET_ROOMS_SUCCESS = '[Room] Get Rooms Success',
  GET_ROOMS_FAILURE = '[Room] Get Rooms Failure',
  GET_ROOMS_WITH_OFFSET = '[Room] Get Room With Offset',
  GET_ROOMS_WITH_OFFSET_SUCCESS = '[Room] Get Room With Offset Success',
  GET_ROOMS_WITH_OFFSET_FAILURE = '[Room] Get Room With Offset Failure',
}
