export enum ActionTypes {
  GET_ROOMS = '[Room] Get Rooms',
  GET_ROOMS_SUCCESS = '[Room] Get Rooms Success',
  GET_ROOMS_FAILURE = '[Room] Get Rooms Failure',
  GET_ROOMS_WITH_OFFSET = '[Room] Get Room With Offset',
  GET_ROOMS_WITH_OFFSET_SUCCESS = '[Room] Get Room With Offset Success',
  GET_ROOMS_WITH_OFFSET_FAILURE = '[Room] Get Room With Offset Failure',
  GET_MESSAGES = '[Message] Get Messages',
  GET_MESSAGES_SUCCESS = '[Message] Get Messages Success',
  GET_MESSAGES_FAILURE = '[Message] Get Messages Failure',
  GET_MESSAGES_WITH_OFFSET = '[Message] Get Messages With Offset',
  GET_MESSAGES_WITH_OFFSET_SUCCESS = '[Message] Get Messages With Offset Success',
  GET_MESSAGES_WITH_OFFSET_FAILURE = '[Message] Get Messages With Offset Failure',
  CREATE_MESSAGE = '[Message] Create Message',
  CREATE_MESSAGE_SUCCESS = '[Message] Create Message Success',
  CREATE_MESSAGE_FAILURE = '[Message] Create Message Failure',
}
