/**
 * Writes `src/i18n/displayNameData.ts`: every language and country the app
 * knows, named in each interface locale.
 *
 * The names used to come from `Intl.DisplayNames` at runtime, which Hermes
 * does not ship on iOS or Android — so the web build showed "Almanca" to a
 * Turkish reader and the phone showed "German". Node carries full ICU, so the
 * same CLDR names are read here once and committed.
 *
 * Unlike `gen:strings` there is no `--check` in CI: Node's CLDR moves with the
 * Node version, and a runner picking up a newer 24.x would fail the build over
 * a renamed country nobody asked to change. Rerun it when `languages.ts` or
 * `countries.ts` gains a code: until then the new code shows its English name
 * in every locale. A removed code is caught by `displayNames.test.ts`.
 *
 * Run: `pnpm --filter @langx/mobile gen:names` from the repo root.
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { COUNTRIES, LANGUAGES, SUPPORTED_LOCALES } from '@langx/shared'
import { format, resolveConfig } from 'prettier'

const OUT = fileURLToPath(new URL('../src/i18n/displayNameData.ts', import.meta.url))

/**
 * Only names that differ from the English one in `@langx/shared` are kept:
 * the lookup falls back to that name anyway, and "Afrikaans" written out
 * seven times is bytes in every bundle for nothing. A code CLDR has no name
 * for comes back from `of()` unchanged and is dropped for the same reason.
 */
function namesFor(
  locale: string,
  type: 'language' | 'region',
  entries: readonly { code: string; name: string }[],
): Record<string, string> {
  const names = new Intl.DisplayNames([locale], { type })
  const out: Record<string, string> = {}
  for (const { code, name } of entries) {
    const localized = names.of(code)
    if (!localized || localized.toLowerCase() === code.toLowerCase() || localized === name) continue
    out[code] = localized
  }
  return out
}

const tables = Object.fromEntries(
  SUPPORTED_LOCALES.filter((locale) => locale !== 'en').map((locale) => [
    locale,
    {
      languages: namesFor(locale, 'language', LANGUAGES),
      countries: namesFor(locale, 'region', COUNTRIES),
    },
  ]),
)

const source = `/**
 * Generated by \`apps/mobile/scripts/build-display-names.ts\` from CLDR
 * ${process.versions.cldr} (Node ${process.version}). Do not edit by hand; rerun:
 *
 *   pnpm --filter @langx/mobile gen:names
 *
 * English is absent on purpose: its names are the ones in \`@langx/shared\`.
 */
import type { Locale } from '@langx/shared'

export interface NameTable {
  languages: Readonly<Record<string, string>>
  countries: Readonly<Record<string, string>>
}

export const DISPLAY_NAMES: Record<Exclude<Locale, 'en'>, NameTable> = ${JSON.stringify(tables)}
`

// tsx runs this as CommonJS, where top-level await is not allowed.
void resolveConfig(OUT)
  .then((config) => format(source, { ...config, filepath: OUT }))
  .then((formatted) => {
    writeFileSync(OUT, formatted)
    console.log(`wrote ${OUT}`)
  })
