export enum ActionTypes {
  LOGIN = '[Auth] Login',
  LOGIN_SUCCESS = '[Auth] Login Success',
  LOGIN_FAILURE = '[Auth] Login Failure',
  LOGIN_WITH_JWT = '[Auth] Login With JWT',
  LOGIN_WITH_JWT_SUCCESS = '[Auth] Login With JWT Success',
  LOGIN_WITH_JWT_FAILURE = '[Auth] Login With JWT Failure',
  ISLOGGEDIN = '[Auth] IsLoggedIn',
  ISLOGGEDIN_SUCCESS = '[Auth] IsLoggedIn Success',
  ISLOGGEDIN_SUCCESS_COMPLETE_REGISTRATION = '[Auth] IsLoggedIn Success Complete Registration',
  ISLOGGEDIN_FAILURE = '[Auth] IsLoggedIn Failure',
  REGISTER = '[Auth] Register',
  REGISTER_SUCCESS = '[Auth] Register Success',
  REGISTER_FAILURE = '[Auth] Register Failure',
  COMPLETE_REGISTRATION = '[Auth] Complete Registration',
  COMPLETE_REGISTRATION_SUCCESS = '[Auth] Complete Registration Success',
  COMPLETE_REGISTRATION_FAILURE = '[Auth] Complete Registration Failure',
  LANGUAGE_SELECTION = '[Auth] Language Selection',
  LANGUAGE_SELECTION_SUCCESS = '[Auth] Language Selection Success',
  LANGUAGE_SELECTION_FAILURE = '[Auth] Language Selection Failure',
  UPDATE_LANGUAGE_ARRAY = '[Auth] Update Language Array',
  UPDATE_LANGUAGE_ARRAY_SUCCESS = '[Auth] Update Language Array Success',
  UPDATE_LANGUAGE_ARRAY_FAILURE = '[Auth] Update Language Array Failure',
  LOGOUT = '[Auth] Logout',
  LOGOUT_SUCCESS = '[Auth] Logout Success',
  LOGOUT_FAILURE = '[Auth] Logout Failure',
}
