export enum ActionTypes {
  GET_ROOM_BY_ID = '[Room] Get Room By Id',
  GET_ROOM_BY_ID_SUCCESS = '[Room] Get Room By Id Success',
  GET_ROOM_BY_ID_FAILURE = '[Room] Get Room By Id Failure',
  FILL_ROOM_BY_ID_WITH_USER_DATA_SUCCESS = '[Room] Fill Room By Id With User Data Success',
  FILL_ROOM_BY_ID_WITH_USER_DATA_FAILURE = '[Room] Fill Room By Id With User Data Failure',
  FILL_ROOM_BY_ID_WITH_MESSAGES_SUCCESS = '[Room] Fill Room By Id With Messages Success',
  FILL_ROOM_BY_ID_WITH_MESSAGES_FAILURE = '[Room] Fill Room By Id With Messages Failure',
  GET_ROOM = '[Room] Get Room',
  GET_ROOM_SUCCESS = '[Room] Get Room Success',
  GET_ROOM_FAILURE = '[Room] Get Room Failure',
  CREATE_ROOM = '[Room] Create Room',
  CREATE_ROOM_SUCCESS = '[Room] Create Room Success',
  CREATE_ROOM_FAILURE = '[Room] Create Room Failure',
}
