export enum ActionTypes {
  GET_ROOMS = '[Rooms] Get Rooms',
  GET_ROOMS_SUCCESS = '[Rooms] Get Rooms Success',
  GET_ROOMS_FAILURE = '[Rooms] Get Rooms Failure',
  GET_ROOMS_WITH_OFFSET = '[Rooms] Get Room With Offset',
  GET_ROOMS_WITH_OFFSET_SUCCESS = '[Rooms] Get Room With Offset Success',
  GET_ROOMS_WITH_OFFSET_FAILURE = '[Rooms] Get Room With Offset Failure',
  // FILL_ROOMS_WITH_USER_DATA_SUCCESS = '[Rooms] Fill Rooms With User Data Success',
  // FILL_ROOMS_WITH_USER_DATA_FAILURE = '[Rooms] Fill Rooms With User Data Failure',
  // FILL_ROOMS_WITH_MESSAGES_SUCCESS = '[Rooms] Fill Rooms With Messages Success',
  // FILL_ROOMS_WITH_MESSAGES_FAILURE = '[Rooms] Fill Rooms With Messages Failure',
  FILL_ROOMS_WITH_OFFSET_WITH_USER_DATA_SUCCESS = '[Rooms] Fill Rooms With Offset With User Data Success',
  FILL_ROOMS_WITH_OFFSET_WITH_USER_DATA_FAILURE = '[Rooms] Fill Rooms With Offset With User Data Failure',
  FILL_ROOMS_WITH_OFFSET_WITH_MESSAGES_SUCCESS = '[Rooms] Fill Rooms With Offset With Messages Success',
  FILL_ROOMS_WITH_OFFSET_WITH_MESSAGES_FAILURE = '[Rooms] Fill Rooms With Offset With Messages Failure',
}
