export enum ActionTypes {
  GET_ROOM_BY_ID = '[Room] Get Room By Id',
  GET_ROOM_BY_ID_SUCCESS = '[Room] Get Room By Id Success',
  GET_ROOM_BY_ID_FAILURE = '[Room] Get Room By Id Failure',
  GET_ROOM = '[Room] Get Room',
  GET_ROOM_SUCCESS = '[Room] Get Room Success',
  GET_ROOM_FAILURE = '[Room] Get Room Failure',
  CREATE_ROOM = '[Room] Create Room',
  CREATE_ROOM_SUCCESS = '[Room] Create Room Success',
  CREATE_ROOM_FAILURE = '[Room] Create Room Failure',
  CREATE_ROOM_INITIAL_STATE = '[Room] Create Room Initial State',
  UPDATE_ROOM = '[Room] Update Room',
  UPDATE_ROOM_SUCCESS = '[Room] Update Room Success',
  UPDATE_ROOM_FAILURE = '[Room] Update Room Failure',
  ARCHIVE_ROOM = '[Room] Archive Room',
  ARCHIVE_ROOM_SUCCESS = '[Room] Archive Room Success',
  ARCHIVE_ROOM_FAILURE = '[Room] Archive Room Failure',
  ARCHIVE_ROOM_INITIAL_STATE = '[Room] Archive Room Initial State',
  UNARCHIVE_ROOM = '[Room] Unarchive Room',
  UNARCHIVE_ROOM_SUCCESS = '[Room] Unarchive Room Success',
  UNARCHIVE_ROOM_FAILURE = '[Room] Unarchive Room Failure',
  UNARCHIVE_ROOM_INITIAL_STATE = '[Room] Unarchive Room Initial State',
  CLEAR_ERRORS = '[Room] Clear Errors',
}
