export enum ActionTypes {
  GET_CURRENT_USER = '[User] Get Current User',
  GET_CURRENT_USER_SUCCESS = '[User] Get Current User Success',
  GET_CURRENT_USER_FAILURE = '[User] Get Current User Failure',
  UPDATE_CURRENT_USER = '[User] Update Current User',
  UPDATE_CURRENT_USER_SUCCESS = '[User] Update Current User Success',
  UPDATE_CURRENT_USER_FAILURE = '[User] Update Current User Failure',
  GET_USER_BY_ID = '[User] Get User',
  GET_USER_BY_ID_SUCCESS = '[User] Get User Success',
  GET_USER_BY_ID_FAILURE = '[User] Get User Failure',
  REPORT_USER = '[User] Report User',
  REPORT_USER_SUCCESS = '[User] Report User Success',
  REPORT_USER_FAILURE = '[User] Report User Failure',
  REPORT_USER_INITIAL_STATE = '[User] Report User Initial State',
}
