/**
 * Regenerates `src/email/inlineAssets.ts` from the files in `src/email/assets/`.
 *
 * The images every email shows travel *inside* the mail as inline attachments
 * (see the generated file's header for why), and the API ships as one bundled
 * `dist/index.js` with no files beside it — so the bytes are inlined into a
 * module rather than read from disk at runtime. Run this after changing an
 * image:
 *
 *   pnpm --filter @langx/api exec tsx scripts/inline-email-assets.ts
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const ASSETS_DIR = join(import.meta.dirname, '../src/email/assets')
const OUT = join(import.meta.dirname, '../src/email/inlineAssets.ts')

const CONTENT_TYPES: Record<string, string> = { png: 'image/png', jpg: 'image/jpeg' }

const files = readdirSync(ASSETS_DIR).sort()
const entries = files.map((filename) => {
  const extension = filename.split('.').pop() ?? ''
  const contentType = CONTENT_TYPES[extension]
  if (!contentType) throw new Error(`${filename}: no content type for .${extension}`)
  const base64 = readFileSync(join(ASSETS_DIR, filename)).toString('base64')
  const cid = `langx-${filename.replace(/\.[a-z]+$/, '')}`
  return { cid, filename, contentType, base64 }
})

const body = entries
  .map(
    // One literal per image rather than a chain of short ones: a few thousand
    // `+` nodes are deeper than prettier's parser can walk, and the file is
    // ignored by prettier for the same reason.
    ({ cid, filename, contentType, base64 }) => `  {
    cid: '${cid}',
    filename: '${filename}',
    contentType: '${contentType}',
    base64: '${base64}',
  },`,
  )
  .join('\n')

writeFileSync(
  OUT,
  `/**
 * GENERATED by \`scripts/inline-email-assets.ts\` from \`src/email/assets/\`.
 * Do not edit; change the image and rerun the script.
 *
 * The images every email shows, as bytes rather than links.
 *
 * They used to be \`<img src="https://langx.io/…">\`, and were missing from
 * most inboxes: Outlook blocks remote images until somebody clicks "download
 * pictures", Apple Mail does the same with remote content off, and the app's
 * own file preview does too. Gmail showed them only because it fetches
 * through its own proxy. An inline attachment referenced as \`cid:\` is shown
 * by all of them without asking, because it arrived with the mail. \`data:\`
 * URIs would have been simpler and Gmail strips them.
 *
 * \`ResendEmailSender\` attaches whichever of these a message's HTML
 * references; templates and campaign bodies only have to use the \`cid:\` src.
 */
export interface InlineAsset {
  cid: string
  filename: string
  contentType: string
  base64: string
}

export const INLINE_ASSETS: readonly InlineAsset[] = [
${body}
]
`,
)
console.log(`wrote ${entries.length} assets to ${OUT}`)
for (const entry of entries) console.log(`  cid:${entry.cid}  (${entry.filename})`)
