const {
  withDangerousMod,
  withProjectBuildGradle,
  withSettingsGradle,
} = require('expo/config-plugins')
const { cpSync, rmSync } = require('node:fs')
const { join } = require('node:path')

/**
 * Wires the Wear OS app into the generated Android project.
 *
 * `android/` is regenerated by `expo prebuild` and is not committed, so the
 * module cannot live there — exactly the problem `@bacons/apple-targets`
 * solves on the Apple side by keeping Swift in `apps/mobile/targets/`. This is
 * the same arrangement with fewer moving parts: `apps/mobile/wear/` is the
 * source of record, and this copies it in and adds one line to
 * `settings.gradle`.
 *
 * It is deliberately not a general-purpose plugin. There is one module, its
 * name is known, and a configurable version of this would be more code than
 * the thing it configures.
 */
const withWearApp = (config) => {
  config = withDangerousMod(config, [
    'android',
    (modConfig) => {
      const from = join(modConfig.modRequest.projectRoot, 'wear')
      const to = join(modConfig.modRequest.platformProjectRoot, 'wear')

      /*
       * Removed first, not merged. A file deleted from `apps/mobile/wear/`
       * would otherwise survive in the generated copy until someone ran
       * `prebuild --clean`, and a stale Kotlin file that still compiles is the
       * kind of thing that is found weeks later.
       */
      rmSync(to, { recursive: true, force: true })
      cpSync(from, to, { recursive: true })
      return modConfig
    },
  ])

  config = withSettingsGradle(config, (modConfig) => {
    if (modConfig.modResults.contents.includes("include ':wear'")) return modConfig
    modConfig.modResults.contents += "\ninclude ':wear'\n"
    return modConfig
  })

  /*
   * Compose needs its own Kotlin compiler plugin since Kotlin 2.0, and the
   * version has to match the Kotlin the rest of the build uses — Expo pins
   * 2.1.20, so that is what goes here. A mismatch fails with a message about
   * the *compiler* rather than about this line, which is why the version is
   * written next to the reason rather than left to a catalogue.
   *
   * On the root project's buildscript because the wear module applies the
   * plugin by id; a module cannot put its own plugin on the classpath.
   */
  return withProjectBuildGradle(config, (modConfig) => {
    const classpath = "    classpath('org.jetbrains.kotlin:compose-compiler-gradle-plugin:2.1.20')"
    if (modConfig.modResults.contents.includes('compose-compiler-gradle-plugin')) return modConfig
    modConfig.modResults.contents = modConfig.modResults.contents.replace(
      "    classpath('org.jetbrains.kotlin:kotlin-gradle-plugin')",
      `    classpath('org.jetbrains.kotlin:kotlin-gradle-plugin')\n${classpath}`,
    )
    return modConfig
  })
}

module.exports = withWearApp
