import { chromium } from 'playwright'
const B = 'http://localhost:8081'
const browser = await chromium.launch({ args: ['--no-sandbox'] })
const ctx = await browser.newContext({ viewport: { width: 800, height: 1100 }, deviceScaleFactor: 2 })
const page = await ctx.newPage()
await page.goto(`${B}/sign-up`, { waitUntil: 'load', timeout: 180000 })
await page.waitForTimeout(9000)
const cb = page.getByRole('checkbox')
console.log('checkbox present :', await cb.count())
const btn = page.locator('[role="button"]').last()
await page.waitForSelector('input', { timeout: 60000 })
await page.locator('input').nth(0).fill('Test Person')
await page.locator('input').nth(1).fill('nobody@test.langx.invalid')
await page.locator('input[type="password"]').nth(0).fill((process.env.SHARE_PASSWORD ?? 'correct horse battery staple'))
await page.locator('input[type="password"]').nth(1).fill((process.env.SHARE_PASSWORD ?? 'correct horse battery staple'))
await page.waitForTimeout(1500)
console.log('button before tick:', await btn.isDisabled().catch(() => 'n/a'), '| aria', await btn.getAttribute('aria-disabled'))
await page.screenshot({ path: './shots/signup-unticked.png' })
await cb.first().click()
await page.waitForTimeout(1500)
console.log('button after tick :', await btn.getAttribute('aria-disabled'))
console.log('checkbox state    :', await cb.first().getAttribute('aria-checked'))
await page.screenshot({ path: './shots/signup-ticked.png' })
await browser.close()
