import { chromium } from 'playwright'
const [name, value] = process.env.COOKIE.split('=')
const browser = await chromium.launch({ args: ['--no-sandbox'] })
const ctx = await browser.newContext({ viewport: { width: 420, height: 900 } })
await ctx.addCookies([{ name, value, domain: 'localhost', path: '/', httpOnly: true, sameSite: 'Lax' }])
const page = await ctx.newPage()
await page.goto('http://localhost:8082/corrections', { waitUntil: 'domcontentloaded', timeout: 240000 })
await page.waitForTimeout(22000)
await page.getByText('Posts', { exact: true }).first().click()
await page.waitForTimeout(3000)
await page.getByText('I go to the store yesterday').first().click()
await page.waitForTimeout(5000)
console.log('OPENED', page.url())
// The app's own back arrow, not the browser's history.
const back = page.locator('[aria-label="Back"], [aria-label="Geri"]').first()
await back.click()
await page.waitForTimeout(4000)
console.log('APP-BACK-TO', page.url())
console.log('TEXT', JSON.stringify((await page.evaluate(() => document.body.innerText)).slice(0, 120)))
await page.screenshot({ path: './shots/writing-4-appback.png' })
await browser.close()
