import { Models } from 'react-native-appwrite';
import { Language } from './Language';
import { Streak } from './Streak';

export type User = Models.Document & {
  name: string;
  country: string;
  countryCode: string;
  gender: string;
  birthdate: Date;
  username: string;
  languageArray?: string[];
  motherLanguages?: string[];
  studyLanguages?: string[];
  languages?: Language[];
  badges?: string[];
  aboutMe?: string;
  lastSeen?: Date;
  totalUnseen?: number;
  totalUnseenArchived?: number;
  notifications?: string[];
  notificationsArray?: string[];
  blockedUsers?: string[];
  archivedRooms?: string[];
  privacy?: string[];
  contributors?: string[];
  sponsor?: boolean;
  streaks?: Streak;
  profilePic?: string;
  otherPics?: string[];
};
